config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create] do
     resource :imitations, only: [:new]
  end

  delete '/imitations', to: 'imitations#destroy', as: 'imitations'

  resource :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

  namespace :admin do
    resources :users
  end

 
  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index 
    @movies =  Movie.all

    
    if params[:search_title] == "" && params[:search_director] == "" && params[:search_time] == "runtime_in_minutes > 0"
      @movies = Movie.all
    elsif params[:search_title] || params[:search_director] || params[:search_time]
      @movies = Movie.search(
        params[:search_title],
        params[:search_director],
        params[:search_time]
        ).order("created_at DESC")
   
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(
      title: params[:movie][:title],
      director: params[:movie][:director],
      runtime_in_minutes: params[:movie][:runtime_in_minutes],
      description: params[:movie][:description],
      poster_image_url: params[:movie][:poster_image_url],
      # remote_image_url: params[:movie][:remote_image_url],
      # local_image_url: params[:movie][:local_image_url],
      release_date: params[:movie][:release_date]  
    )

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :release_date)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do | msg | %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <div>
      <%= f.label "title" %><br>
      <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
      <%= f.label "director" %><br>
      <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
 <!--  <div>
    <%= f.label "remote_image_url" %><br>
    <%= f.url_field "remote_image_url" %>
  <div> -->
  <!-- <div>
      <%= f.label "local_image_url" %><br>
      <%= f.file_field "local_image_url" %>
  </div> -->
  <div>
    <%= f.label "poster_image_url" %>
    <%= f.file_field "poster_image_url" %>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %> </h2>
  <h3><%= movie.director %> | <%= formatted_date(movie.release_date) %></h3>
  <h4><%= movie.runtime_in_minutes %> minutes long | <%= movie.review_average %>/10</h4>
  <p><%= movie.description %></p>

app/views/movies/edit.html.erb
<h1>Edit movie</h1>

<%= link_to "Back to this movie", movies_path(@movie) %>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1><%= link_to "Movies", movies_path %></h1>

<%= form_tag(movies_path, :method => "get", id: "search_box" ) do %>
  <%= label_tag(:search_title, "Search Title:") %>
  <%= text_field_tag :search_title, params[:search_title] %><br>
  <%= label_tag(:search_director, "Director:") %>
  <%= text_field_tag :search_director, params[:search_director] %><br>
  <%= label_tag(:search_time, "Movie runtime") %>
  <%= select_tag(:search_time, options_for_select([["None", "runtime_in_minutes > 0"],["< 90mins", "0 < runtime_in_minutes AND runtime_in_minutes < 90"], ["90 to 120mins", "90 < runtime_in_minutes AND runtime_in_minutes < 120"], ["> 120mins", "runtime_in_minutes >= 120" ]])) %>
  <%= submit_tag("Search", :name => nil) %>
<% end %>

<%= link_to "Submit a movie!", new_movie_path %>

<%= render partial: "movie", collection: @movies %>

app/views/movies/new.html.erb
 <%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie!</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= link_to image_tag(@movie.poster_image_url), movie_path(@movie) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4><%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes | <%= @movie.review_average %>/10</h4>
<p><%= @movie.description %></p>

<h3> Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do | review | %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %></p>
    <small><%= review.user.email %></small><br>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p> Please <%= link_to "Log In", new_session_path %> to see reviews and add your own.</p>
<% end %>