config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create] do
     resource :imitations, only: [:new]
  end

  delete '/imitations', to: 'imitations#destroy', as: 'imitations'

  resource :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

  namespace :admin do
    resources :users
  end

 
  

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true

  validates :firstname, presence: true

  validates :lastname, presence: true

  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access, :admin_access

  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
  
    if @user.save
       redirect_to admin_users_path, notice: "New user #{@user.firstname} with email #{@user.email} created."
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    UserMailer.email_removed_user(@user).deliver
    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :is_admin, :password, :password_confirmation)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id 
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Sign up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do | msg | %>
            <li><%= msg  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>
    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>
    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>
    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>
    <div>
      <%= f.label "password_confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>

app/views/admin/users/edit.html.erb
<h1> Admin edit a user </h1>
  <%= form_for @user, url: admin_user_path(@user), html: {method: :put } do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do | msg | %>
            <li><%= msg  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>
    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>
    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>
    <div>
      <%= f.label "is_admin", "Administrator" %>
      <%= f.check_box "is_admin" %>
    </div>
    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>
    <div>
      <%= f.label "password_confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>

app/views/admin/users/index.html.erb
<h1>Site Administration</h1>

<p> Welcome <%= current_user.full_name %></p>
<%= link_to "Add new user", new_admin_user_path %> 
<% @users.each do | user | %>
  <p> <%= link_to user.full_name, admin_user_path(user) %></p>
  <p>Has submitted <%= pluralize(user.reviews.size, "review") %> </p>
  <span><%= user.firstname %></span><span><%= user.lastname %></span><span><%= user.email %></span>
    <% if user.is_admin %>
      <span>Administrator</span>
    <% end %>
<% end %>

app/views/admin/users/new.html.erb
<h1>Add a user</h1>
  <%= form_for @user, url: admin_users_path, html: { method: :post } do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do | msg | %>
            <li><%= msg  %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>
    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>
    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>
    <div>
      <%= f.label "is_admin", "Administrator" %>
      <%= f.check_box "is_admin" %>
    </div>
    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>
    <div>
      <%= f.label "password_confirmation" %><br>
      <%= f.password_field "password_confirmation" %>
    </div>
    <div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.full_name %><h1>
<h3><%= link_to "Edit User", edit_admin_user_path(@user) %></h3>
<h3><%= link_to "Delete", admin_user_path(@user), method: :delete, confirm: "Are you sure you want to delete this user?" %></h3>
<h4><%= link_to "Imitate", new_user_imitations_path(params[:id])%></h4>